name: Continuous Deployment Integration
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  BUILD_DEPLOY_ON_S3:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploying on ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Extract branch name
        shell: bash
        run: echo ::set-output name=branch::${{github.event.pull_request.head.ref}}
        id: branch

      - name: Configuring AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-south-1'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: export BRANCH_NAME=${{ steps.branch.outputs.branch }} && yarn build:uat

      - name: Deploy
        run: aws s3 sync ./build s3://itunessearch-demo/${{ steps.branch.outputs.branch }}