name: CI pipeline for iTunes app

on:
  push:
    branches: [master]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Extract branch name
        shell: bash
        run: echo ::set-output name=branch::${{github.event.pull_request.base.ref}}
        id: branch

      - name: Install Deps
        run: yarn --prefer-offline

      - name: Lint
        run: yarn lint

      - name: Output
        run: ${{github.base_ref}}

      - name: OuNew tput
        run: ${{github.event.pull_request}}
